/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AppMeta {
  key: string | null;
  updatedAt: Generated<string>;
  value: string;
}

export interface Conversation {
  createdAt: Generated<string>;
  folderId: string | null;
  id: string | null;
  modelApi: string | null;
  modelId: string | null;
  provider: string | null;
  reasoningEffort: string | null;
  reasoningSummary: Generated<number>;
  systemPrompt: string | null;
  title: string;
  updatedAt: Generated<string>;
  userId: string;
  verbosity: string | null;
}

export interface ConversationTag {
  conversationId: string;
  tagId: string;
}

export interface Folder {
  createdAt: Generated<string>;
  id: string | null;
  name: string;
  userId: string;
}

export interface Message {
  conversationId: string;
  createdAt: Generated<string>;
  id: string | null;
  inputTokens: number | null;
  model: string | null;
  outputTokens: number | null;
  parts: string | null;
  role: string;
  status: Generated<string>;
  text: Generated<string>;
}

export interface Preset {
  createdAt: Generated<string>;
  id: string | null;
  modelApi: string;
  modelId: string;
  name: string;
  provider: string;
  reasoningEffort: string | null;
  reasoningSummary: Generated<number>;
  scope: Generated<string>;
  systemPrompt: string | null;
  userId: string;
  verbosity: string | null;
}

export interface ProviderConfig {
  apiKey: string | null;
  baseUrl: string | null;
  enabledModels: Generated<string>;
  provider: string | null;
  updatedAt: Generated<string>;
}

export interface Session {
  createdAt: string;
  expiresAt: string;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface Tag {
  createdAt: Generated<string>;
  id: string | null;
  name: string;
  userId: string;
}

export interface User {
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: string;
  updatedAt: string;
}

export interface UserSetting {
  defaultApi: string | null;
  defaultModelId: string | null;
  defaultProvider: string | null;
  updatedAt: Generated<string>;
  userId: string | null;
}

export interface Verification {
  createdAt: string;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string;
  value: string;
}

export interface DB {
  account: Account;
  app_meta: AppMeta;
  conversation: Conversation;
  conversation_tag: ConversationTag;
  folder: Folder;
  message: Message;
  preset: Preset;
  provider_config: ProviderConfig;
  session: Session;
  tag: Tag;
  user: User;
  user_setting: UserSetting;
  verification: Verification;
}
