/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export interface Account {
	accessToken: string | null;
	accessTokenExpiresAt: string | null;
	accountId: string;
	createdAt: string;
	id: string;
	idToken: string | null;
	issuer: string;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	refreshTokenExpiresAt: string | null;
	scope: string | null;
	updatedAt: string;
	userId: string;
}

export interface Apikey {
	configId: string;
	createdAt: string;
	enabled: number | null;
	expiresAt: string | null;
	id: string;
	key: string;
	lastRefillAt: string | null;
	lastRequest: string | null;
	metadata: string | null;
	name: string | null;
	permissions: string | null;
	prefix: string | null;
	rateLimitEnabled: number | null;
	rateLimitMax: number | null;
	rateLimitTimeWindow: number | null;
	referenceId: string;
	refillAmount: number | null;
	refillInterval: number | null;
	remaining: number | null;
	requestCount: number | null;
	start: string | null;
	updatedAt: string;
}

export interface AppMeta {
	key: string | null;
	updatedAt: Generated<string>;
	value: string;
}

export interface Attachment {
	byteSize: number;
	createdAt: Generated<string>;
	filename: string;
	height: number | null;
	id: string | null;
	kind: string;
	mimeType: string;
	pageCount: number | null;
	sha256: string;
	storageKey: string;
	userId: string;
	width: number | null;
}

export interface Conversation {
	autoExecuteTools: Generated<number>;
	createdAt: Generated<string>;
	displayMode: string | null;
	endpointId: string | null;
	folderId: string | null;
	id: string | null;
	modelApi: string | null;
	modelId: string | null;
	provider: string | null;
	reasoningEffort: string | null;
	reasoningSummary: Generated<number>;
	systemPrompt: string | null;
	title: string;
	updatedAt: Generated<string>;
	userId: string;
	verbosity: string | null;
}

export interface ConversationMcpServer {
	conversationId: string;
	enabled: Generated<number>;
	serverId: string;
}

export interface ConversationTag {
	conversationId: string;
	tagId: string;
}

export interface Folder {
	createdAt: Generated<string>;
	id: string | null;
	name: string;
	userId: string;
}

export interface ImageAsset {
	byteSize: number;
	createdAt: Generated<string>;
	filename: string;
	height: number | null;
	id: string | null;
	kind: string;
	mimeType: string;
	sha256: string;
	sourceAssetId: string | null;
	storageKey: string;
	userId: string;
	width: number | null;
	workspaceId: string;
}

export interface ImageAttempt {
	api: string;
	aspectRatio: string | null;
	costMicros: number | null;
	createdAt: Generated<string>;
	endpointId: string;
	errorMessage: string | null;
	finishedAt: string | null;
	id: string | null;
	modelId: string;
	prompt: string;
	provider: string;
	requestKey: string;
	resolution: string | null;
	resultAssetId: string | null;
	retryOfAttemptId: string | null;
	sourceAssetId: string | null;
	startedAt: string | null;
	status: Generated<string>;
	usageJson: string | null;
	userId: string;
	workspaceId: string;
}

export interface ImageWorkspace {
	aspectRatio: string | null;
	createdAt: Generated<string>;
	id: string | null;
	modelId: string | null;
	resolution: string | null;
	title: string;
	updatedAt: Generated<string>;
	userId: string;
}

export interface ImpersonationSession {
	adminSessionId: string | null;
	expiresAt: number;
	targetUserId: string;
	updatedAt: number;
}

export interface McpServer {
	createdAt: string;
	enabled: Generated<number>;
	headers: Generated<string>;
	id: string | null;
	name: string;
	updatedAt: string;
	url: string;
	userId: string | null;
}

export interface MessageAttachment {
	attachmentId: string;
	messageId: string;
	ordinal: number;
}

export interface Preset {
	createdAt: Generated<string>;
	endpointId: string | null;
	id: string | null;
	modelApi: string;
	modelId: string;
	name: string;
	provider: string;
	reasoningEffort: string | null;
	reasoningSummary: Generated<number>;
	scope: Generated<string>;
	systemPrompt: string | null;
	userId: string;
	verbosity: string | null;
}

export interface ProviderConfig {
	apiKey: string | null;
	baseUrl: string | null;
	enabledModels: Generated<string>;
	endpoints: Generated<string>;
	imageModels: Generated<string>;
	provider: string | null;
	updatedAt: Generated<string>;
}

export interface Session {
	createdAt: string;
	expiresAt: string;
	id: string;
	ipAddress: string | null;
	token: string;
	updatedAt: string;
	userAgent: string | null;
	userId: string;
}

export interface Skill {
	content: string;
	createdAt: Generated<string>;
	description: string;
	exposed: Generated<number>;
	id: string | null;
	name: string;
	updatedAt: Generated<string>;
	userId: string;
}

export interface SourceCategory {
	category: string | null;
	domain: string | null;
	source: string;
	updatedAt: Generated<string>;
}

export interface Tag {
	createdAt: Generated<string>;
	id: string | null;
	name: string;
	userId: string;
}

export interface User {
	createdAt: string;
	email: string;
	emailVerified: number;
	id: string;
	image: string | null;
	isDisabled: number;
	name: string;
	role: string;
	updatedAt: string;
}

export interface UserMcpServerPreference {
	enabled: Generated<number>;
	serverId: string;
	userId: string;
}

export interface UserSetting {
	defaultApi: string | null;
	defaultDisplayMode: string | null;
	defaultEndpointId: string | null;
	defaultModelId: string | null;
	defaultPresetId: string | null;
	defaultProvider: string | null;
	updatedAt: Generated<string>;
	userId: string | null;
}

export interface Verification {
	createdAt: string;
	expiresAt: string;
	id: string;
	identifier: string;
	updatedAt: string;
	value: string;
}

export interface DB {
	account: Account;
	apikey: Apikey;
	app_meta: AppMeta;
	attachment: Attachment;
	conversation: Conversation;
	conversation_mcp_server: ConversationMcpServer;
	conversation_tag: ConversationTag;
	folder: Folder;
	image_asset: ImageAsset;
	image_attempt: ImageAttempt;
	image_workspace: ImageWorkspace;
	impersonation_session: ImpersonationSession;
	mcp_server: McpServer;
	message_attachment: MessageAttachment;
	preset: Preset;
	provider_config: ProviderConfig;
	session: Session;
	skill: Skill;
	source_category: SourceCategory;
	tag: Tag;
	user: User;
	user_mcp_server_preference: UserMcpServerPreference;
	user_setting: UserSetting;
	verification: Verification;
}
